#!/usr/bin/node

const puppeteer = require('puppeteer');

(async () => {
  const args=[
    '--no-default-browser-check',
    '--no-first-run',
    '--autoplay-policy=no-user-gesture-required',
    '--kiosk',
    '--noerrdialogs',
    '--start-fullscreen',
    '--disable-infobars',
    '--disable-session-crashed-bubble',
    '--password-store=basic'
    // '--default-background-color', '000000ff'
    // '--auto-open-devtools-for-tabs'
  ]

  const browser = await puppeteer.launch({
	  args, 
	  headless: false,
	  ignoreDefaultArgs: ['--mute-audio'],
	  defaultViewport: {
      width: 1920,
      height: 1080,
      hasTouch: true
    }
  });
  const page = await browser.newPage();
  await page.evaluate( ()=> {
    document.body.style.background='#000000'
    document.body.style.height='1080px'
  })

  await page.goto('https://nullprogram.com/webgl-particles/');

  setTimeout( (async ()=>{
    await browser.close();
  }), 20000)

})();
